Repository test-fullautomation/robotframework-testsuitesmanagement, pull requests merged in 2022-11, with the labels that each got.

#37 README rst 2 md converter added
  readme.rst2md.py
Labels: enhancement, 0.6.0

#40 Tiny path fix in Test Executor
  test/executerobottest.py
Labels: enhancement, 0.6.0

#36 Refactor code comment format base on genpackagedocs feature
  README.md
  README.rst
  RobotFramework_Testsuites/Config/CConfig.py
  RobotFramework_Testsuites/Keywords/COnFailureHandle.py
  RobotFramework_Testsuites/Keywords/CSetup.py
  RobotFramework_Testsuites/RobotFramework_Testsuites.pdf
  RobotFramework_Testsuites/Utils/CStruct.py
  RobotFramework_Testsuites/Utils/LibListener.py
  RobotFramework_Testsuites/__init__.py
  packagedoc/additional_docs/Description.rst
  packagedoc/additional_docs/Introduction.rst
Labels: documentation, 0.6.0

#43 Updated default robot_config.json file which is using for level 4 config
  RobotFramework_Testsuites/Config/robot_config.json
Labels: 0.6.0
