Repository test-fullautomation/robotframework-testsuitesmanagement, pull requests merged in 2023-01, with the labels that each got.

#63 Documentation updates and fixes
  README.md
  README.rst
  RobotFramework_TestsuitesManagement/Config/CConfig.py
  RobotFramework_TestsuitesManagement/Config/robot_config.json
  RobotFramework_TestsuitesManagement/Config/robot_schema.json
  RobotFramework_TestsuitesManagement/Keywords/CSetup.py
  RobotFramework_TestsuitesManagement/RobotFramework_Testsuites.pdf
  RobotFramework_TestsuitesManagement/RobotFramework_TestsuitesManagement.pdf
  RobotFramework_TestsuitesManagement/Utils/CStruct.py
  RobotFramework_TestsuitesManagement/Utils/LibListener.py
  RobotFramework_TestsuitesManagement/__init__.py
  additions/PythonExtensionsCollection/File/CFile.py
  additions/PythonExtensionsCollection/File/__init__.py
  additions/PythonExtensionsCollection/Folder/CFolder.py
  additions/PythonExtensionsCollection/Folder/__init__.py
  additions/PythonExtensionsCollection/String/CString.py
  additions/PythonExtensionsCollection/String/__init__.py
  additions/PythonExtensionsCollection/Utils/CUtils.py
  additions/PythonExtensionsCollection/Utils/__init__.py
  additions/PythonExtensionsCollection/__init__.py
  additions/PythonExtensionsCollection/version.py
  atest/atest_component/builtin_variable/testsuites/config/builtin_variable_with_config_level_3.json
  atest/atest_component/config_levels/testsuites/level_1_2_3/config/config_level1_03.json
  atest/atest_component/config_levels/testsuites/level_1_2_3/config/config_level1_04.json
  atest/atest_component/config_levels/testsuites/level_2_3/config/config_level2_03.json
  atest/atest_component/config_levels/testsuites/level_2_3/config/config_level2_04.json
  atest/general_config/common/test_config_common.json
  atest/general_config/robot_config_variant_1.json
  atest/general_config/test_config_level_1.json
  atest/resources/atest_libs.py
  config/repository_config.json
  packagedoc/additional_docs/Description.rst
Labels: documentation, enhancement, 0.6.0

#74 Updates version and history
  RobotFramework_TestsuitesManagement/packageversion.py
  packagedoc/additional_docs/History.tex
Labels: documentation, 0.6.0

#73 Namson/features/prepare for release 060
  RobotFramework_TestsuitesManagement/Config/CConfig.py
  RobotFramework_TestsuitesManagement/Config/robot_schema.json
  RobotFramework_TestsuitesManagement/Keywords/CSetup.py
  RobotFramework_TestsuitesManagement/Utils/LibListener.py
Labels: enhancement, 0.6.0

#75 Rework of main documentation
  README.md
  README.rst
  RobotFramework_TestsuitesManagement/RobotFramework_TestsuitesManagement.pdf
  packagedoc/additional_docs/Description.rst
  packagedoc/additional_docs/Description.tex
  packagedoc/additional_docs/History.tex
  packagedoc/additional_docs/Introduction.rst
  packagedoc/additional_docs/Introduction.tex
  packagedoc/additional_docs/ROBFW_AIO_Testsuite_orig.rst
  packagedoc/packagedoc_config.json
Labels: documentation, 0.6.0

#85 Typo fixes; indentations adapted in docstrings; maintenance
  RobotFramework_TestsuitesManagement/Config/CConfig.py
  RobotFramework_TestsuitesManagement/Keywords/CSetup.py
  RobotFramework_TestsuitesManagement/RobotFramework_TestsuitesManagement.pdf
  RobotFramework_TestsuitesManagement/Utils/CStruct.py
  RobotFramework_TestsuitesManagement/Utils/Events/Event.py
  RobotFramework_TestsuitesManagement/Utils/Events/ScopeEvent.py
  RobotFramework_TestsuitesManagement/Utils/Events/__init__.py
  RobotFramework_TestsuitesManagement/Utils/LibListener.py
  RobotFramework_TestsuitesManagement/__init__.py
  RobotFramework_TestsuitesManagement/version.py
Labels: documentation, 0.7.0

#89 Fixed version numbers in test folder; maintenance
  test/config/main_config.json
  test/config/testconfig.json
  test/testsuitesmanagement.robot
Labels: documentation, 0.7.0
